// Catálogo SAT de regímenes fiscales (CFDI 4.0), compartido por Clientes y Facturación.
export const REGIMEN_FISCAL_OPTIONS = [
  { value: "601", label: "601 - Régimen General de Ley Personas Morales" },
  { value: "602", label: "602 - Régimen Simplificado de Ley Personas Morales" },
  { value: "603", label: "603 - Personas Morales con Fines no Lucrativos" },
  { value: "604", label: "604 - Régimen de Pequeños Contribuyentes" },
  { value: "605", label: "605 - Régimen de Sueldos y Salarios e Ingresos Asimilados a Salarios" },
  { value: "606", label: "606 - Régimen de Arrendamiento" },
  { value: "607", label: "607 - Régimen de Enajenación o Adquisición de Bienes" },
  { value: "608", label: "608 - Régimen de los Demás Ingresos" },
  { value: "609", label: "609 - Régimen de Consolidación" },
  { value: "610", label: "610 - Régimen Residentes en el Extranjero sin Establecimiento Permanente en México" },
  { value: "611", label: "611 - Régimen de Ingresos por Dividendos (Socios y Accionistas)" },
  { value: "612", label: "612 - Régimen de las Personas Físicas con Actividades Empresariales y Profesionales" },
  { value: "613", label: "613 - Régimen Intermedio de las Personas Físicas con Actividades Empresariales" },
  { value: "614", label: "614 - Régimen de los Ingresos por Intereses" },
  { value: "615", label: "615 - Régimen de los Ingresos por Obtención de Premios" },
  { value: "616", label: "616 - Sin Obligaciones Fiscales" },
  { value: "617", label: "617 - PEMEX" },
  { value: "618", label: "618 - Régimen Simplificado de Ley Personas Físicas" },
  { value: "619", label: "619 - Ingresos por la Obtención de Préstamos" },
  { value: "620", label: "620 - Sociedades Cooperativas de Producción que Optan por Diferir sus Ingresos" },
  { value: "621", label: "621 - Régimen de Incorporación Fiscal" },
  { value: "622", label: "622 - Régimen de Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras PM" },
  { value: "623", label: "623 - Régimen Opcional para Grupos de Sociedades" },
  { value: "624", label: "624 - Régimen de los Coordinados" },
  { value: "625", label: "625 - Régimen de las Actividades Empresariales con Ingresos a través de Plataformas Tecnológicas" },
  { value: "626", label: "626 - Régimen Simplificado de Confianza" },
];
